export enum OrganisationRole {
  OWNER = "owner",
  CAN_EDIT = "can_edit",
  CAN_READ = "can_read",
  GAMESOCIAL_OWNER = "gamesocial_owner",
  GAMESOCIAL_CAN_EDIT = "gamesocial_can_edit",
  GAMESOCIAL_CAN_READ = "gamesocial_can_read",
  GAMESCAN_OWNER = "gamescan_owner",
  GAMESCAN_CAN_EDIT = "gamescan_can_edit",
  GAMESCAN_CAN_READ = "gamescan_can_read",
  GAMEID_OWNER = "gameid_owner",
  GAMEID_CAN_EDIT = "gameid_can_edit",
  GAMEID_CAN_READ = "gameid_can_read",
  GAMEPAD_OWNER = "gamepad_owner",
  GAMEPAD_CAN_EDIT = "gamepad_can_edit",
  GAMEPAD_CAN_READ = "gamepad_can_read",
  GAMELAUNCHER_OWNER = "gamelauncher_owner",
  GAMELAUNCHER_CAN_EDIT = "gamelauncher_can_edit",
  GAMELAUNCHER_CAN_READ = "gamelauncher_can_write",
}
